name: CI Maven

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Fetch install-mvnd action
        run: |
          mkdir -p .github/actions/install-mvnd
          curl -o .github/actions/install-mvnd/action.yml https://raw.githubusercontent.com/apache/camel/main/.github/actions/install-mvnd/action.yml
      - id: install-mvnd
        uses: ./.github/actions/install-mvnd
      - name: Checkout doodle-build
        uses: actions/checkout@v3
        with:
          repository: org-doodle/doodle-build
          path: org-doodle/doodle-build
      - name: Install doodle-build
        run: mvnd install
        working-directory: org-doodle/doodle-build

      - name: Checkout coding style
        run: mvnd spotless:check

      - name: Build with Maven
        run: mvnd package -B
