name: CI Maven

on:
  push:
    branches: main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Install Doodle Modules
        run: echo "doodle-build doodle-socket" > DOODLE && make install

      - name: Checkout coding style
        run: ./mvnw spotless:check

      - name: Build with Maven
        run: ./mvnw package -B
